---
- name: apply kubernetes manifest file 
  hosts: localhost
  tasks: 
    - name: apply manifest file
      command: "kubectl --kubeconfig=./kubeconfig-k3s.yml apply -k ~/bootcamp-devops-projet/03_kubernetes "