apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-deployment
  labels:
    app: odoo
    env: prod
spec:
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: odoo:17.0
        env:
        - name: USER
          valueFrom:
            secretKeyRef:
              key: user
              name: odoo-secret
        - name: PASSWORD 
          valueFrom:
            secretKeyRef:
              key: password 
              name: odoo-secret 
        - name: HOST 
          valueFrom:
            configMapKeyRef:
              key: host 
              name: odoo-cm
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 8069
        volumeMounts:
        - name: odoo-persitent-storage
          mountPath: /var/lib/odoo
        - name: odoo-persitent-storage-odoo
          mountPath: /etc/odoo
        - name: odoo-persitent-storage-extras
          mountPath: /mnt/extra-addons
      volumes: 
      - name: odoo-persitent-storage
        persistentVolumeClaim:
          claimName: odoo-pvc
      - name: odoo-persitent-storage-odoo
        hostPath: 
          path: /data-odoo/config
      - name: odoo-persitent-storage-extras
        hostPath: 
          path: /data-odoo/addons

