apiVersion: v1
kind: Service
metadata:
  name: odoo-svc
  labels:
    app: odoo
    env: prod
spec:
  selector:
    app: odoo
  ports:
  - port: 8069
    targetPort: 8069
    nodePort: 30010
  type: NodePort
