apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc
  labels: 
    env: prod 
    app: pgadmin 
    type: local
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
