apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-webapp
  labels:
    env: prod 
    app: ic-webapp
spec:
  selector:
    matchLabels:
      app: ic-webapp
  template:
    metadata:
      labels:
        app: ic-webapp
    spec:
      containers:
      - name: ic-webapp
        image: ulrichsteve/ic-webapp:1.0
        env:
        - name: ODOO_URL 
          valueFrom: 
            configMapKeyRef:
              key: odoo_url 
              name: ic-webapp-cm
        - name: PGADMIN_URL 
          valueFrom:
            configMapKeyRef:
              key: pgadmin_url 
              name: ic-webapp-cm
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 8080
