apiVersion: v1
kind: Service
metadata:
  name: ic-webapp-svc
  labels:
    env: prod 
    app: ic-webapp
spec:
  selector:
    app: ic-webapp
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30012
  type: NodePort
