pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials('aws_access_key_id')
        AWS_SECRET_ACCESS_KEY = credentials('aws_secret_access_key')
    }
    stages {
        stage('Build Docker EC2') {
            agent {
                docker { image 'jenkins/jnlp-agent-terraform' }
            }
            steps {
                script {
                    sh '''
                        mkdir -p ~/.aws
                        echo "[default]" > ~/.aws/credentials
                        echo -e "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
                        echo -e "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
                        chmod 400 ~/.aws/credentials
                        cd 02_terraform/
                        terraform init 
                        terraform apply -var="stack=docker" -auto-approve
                        mkdir -p ${WORKSPACE}/shared
                        cp ../04_ansible/host_vars/docker.yaml ${WORKSPACE}/shared/docker.yaml
                    '''
                }
            }
        }
        stage('Ansible deploy on docker vm') {
            agent {
                docker { image 'registry.gitlab.com/robconnolly/docker-ansible:latest' }
            }
            steps {
                script {
                    sh '''
                        cp ${WORKSPACE}/shared/docker.yaml ./04_ansible/host_vars/docker.yaml
                        cd 04_ansible/
                        ansible-playbook playbooks/docker/main.yaml
                    '''
                }
            }
        }
    }
}
