services:
  ic-webapp:
    container_name: ic-webapp
    ports: 
      - 8080:8080
    image: ic-webapp:1.0
    environment:
      - "ODOO_URL=http://44.204.20.223:8069/"
      - "PGADMIN_URL=http://44.204.20.223:80"