---
- name: docker_deploy
  hosts: docker
  become: true
  include_vars:
    file: "host_vars/docker.yaml"
  vars:
    network: webapp-network
  roles:
    - docker
    - icwebapp
    - odoo
    - pgdamin
